parameters:
    darvin_bitrix24.client.class: Darvin\Bitrix24Bundle\Client\Client

services:
    darvin_bitrix24.client:
        class: '%darvin_bitrix24.client.class%'
        arguments:
            - '@eight_points_guzzle.client.darvin_bitrix24'
        calls:
            - [ setLogger, [ '@?logger' ] ]
