parameters:
    darvin_bitrix24.lead_factory.class: Darvin\Bitrix24Bundle\Factory\LeadFactory

services:
    darvin_bitrix24.lead_factory:
        class: '%darvin_order.bitrix24.lead_factory.class%'
        public: true
        arguments:
            - '@darvin_bitrix24.utm.utm_manager'
            - '@property_accessor'
