parameters:
    darvin_bitrix24.repository.crm.lead.class: Darvin\Bitrix24Bundle\Repository\CRM\LeadRepository

services:
    darvin_bitrix24.repository.crm.lead:
        class: '%darvin_bitrix24.repository.crm.lead.class%'
        arguments:
            - '@darvin_bitrix24.client'
