parameters:
    darvin_bitrix24.utm.manager.class: Darvin\Bitrix24Bundle\UTM\UTMManager

    darvin_bitrix24.utm.set_event_subscriber.class: Darvin\Bitrix24Bundle\EventListener\SetUTMSubscriber

services:
    darvin_bitrix24.utm.manager:
        class: '%darvin_bitrix24.utm.manager.class%'
        arguments:
            - '@session'

    darvin_bitrix24.utm.set_event_subscriber:
        class: '%darvin_bitrix24.utm.set_event_subscriber.class%'
        arguments:
            - '@darvin_bitrix24.utm.manager'
        tags:
            - { name: kernel.event_subscriber }
